default: &default
  adapter: postgresql
  encoding: unicode
  timeout: 5000
  username: postgres
  password: password

development:
  <<: *default
  database: budget_development

test:
  <<: *default
  database: budget_test

production:
  <<: *default
  database: budget_production
  username: budget
